### ISSUE TITLE
linuxdeploy + generating appimage + ubuntu 16.04 = core dump

### ISSUE THREAD

**Issue by mzaleczny** [linuxdeploy/linuxdeploy#74] opened 2019-05-01 13:30 UTC
I have the problem with generating AppImage application for very simple program. In Ubuntu 16.04 LTS it crashes with segmentation fault. I tested it also in Ubuntu 18.10 and the same app works just fine.
For a greater insight I provide the app source that can be used to reproduce the error:
https://drive.google.com/open?id=1qYIHfT4BzBrUGhLL3Vv8pxeI-bnTb-3v
File errors.txt contains the output of strace command.
Use build_app_dir.sh to compile and make AppDir for AppImage (in ./build/AppDir).
Use build_app_image.sh to generate AppImage file. This script results with core dump in Ubuntu 16.04 LTS while In 18.10 works properly.

I have to mention that I also tried to build the latest linuxdeploy and AppImage plugin from sources and outputed binaries also results with core dump.

**Comment by TheAssassin** [comment] 2019-05-01 18:30
`--executable=tut` seems unnecessary, it's probably installed already by your `make install` call. I have no time to try it myself now. Can you provide a non-strace log please?

**Comment by mzaleczny** [comment] 2019-05-02 15:25
**executable=tut is required by --create-desktop-file option, if ommited causes error:**
`
linuxdeploy version 1-alpha (git commit ID 5c3a51f), Travis build 365 built on 2019-04-06 03:14:36 UTC

-- Creating basic AppDir structure -- 
Creating directory AppDir/usr/bin/ 
Creating directory AppDir/usr/lib/ 
Creating directory AppDir/usr/share/applications/ 
Creating directory AppDir/usr/share/icons/hicolor/ 
Creating directory AppDir/usr/share/icons/hicolor/16x16/apps/ 
Creating directory AppDir/usr/share/icons/hicolor/32x32/apps/ 
Creating directory AppDir/usr/share/icons/hicolor/64x64/apps/ 
Creating directory AppDir/usr/share/icons/hicolor/128x128/apps/ 
Creating directory AppDir/usr/share/icons/hicolor/256x256/apps/ 
Creating directory AppDir/usr/share/icons/hicolor/scalable/apps/ 

-- Deploying dependencies for existing files in AppDir -- 
Deploying dependencies for ELF file AppDir/usr/bin/tut 
  Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libm.so.6 
  Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libc.so.6 

-- Copying files into AppDir -- 
Setting rpath in ELF file AppDir/usr/bin/tut to $ORIGIN/../lib 

-- Deploying icons -- 
Deploying icon ../tut.png 
WARNING: Could not find copyright files for file ../tut.png using dpkg-query 

-- Copying files into AppDir -- 
Copying file ../tut.png to AppDir/usr/share/icons/hicolor/32x32/apps/tut.png 
ERROR: --create-desktop-file requires at least one executable to be passed 
`

**Non strace output is presented below:**
`
linuxdeploy version 1-alpha (git commit ID 5c3a51f), Travis build 365 built on 2019-04-06 03:14:36 UTC

-- Creating basic AppDir structure -- 
Creating directory AppDir/usr/bin/ 
Creating directory AppDir/usr/lib/ 
Creating directory AppDir/usr/share/applications/ 
Creating directory AppDir/usr/share/icons/hicolor/ 
Creating directory AppDir/usr/share/icons/hicolor/16x16/apps/ 
Creating directory AppDir/usr/share/icons/hicolor/32x32/apps/ 
Creating directory AppDir/usr/share/icons/hicolor/64x64/apps/ 
Creating directory AppDir/usr/share/icons/hicolor/128x128/apps/ 
Creating directory AppDir/usr/share/icons/hicolor/256x256/apps/ 
Creating directory AppDir/usr/share/icons/hicolor/scalable/apps/ 

-- Deploying dependencies for existing files in AppDir -- 
Deploying dependencies for ELF file AppDir/usr/bin/tut 
  Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libm.so.6 
  Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libc.so.6 

-- Deploying executables -- 
Deploying executable tut 
Aborted (core dumped)
`

**Comment by TheAssassin** [comment] 2019-05-02 18:29
This is mostly related to the file `tut` not existing anywhere. Either you point an absolute path, or (*and that's better*) you just write your own desktop file.

In any case, I'll have a look at this.

**Comment by mzaleczny** [comment] 2019-05-03 14:00
You are right! That was the case. The tut binary was not found on the path and it has caused the errors. I created my own desktop file in AppDir/usr/share/applications/ directory and issued command:
../linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage
and everything processed just fine and AppImage was created successfully.

Thanks for Your help.

**Comment by TheAssassin** [comment] 2019-05-05 00:30
Cannot reproduce this. I don't think it's worth investing more time. Closing, can be reopened at any time if needed.

**Closed by TheAssassin** 2019-05-05 00:30 UTC
