### ISSUE TITLE
New cmld arg to specify custom appdata file

### ISSUE THREAD

**Issue by kossebau** [linuxdeploy/linuxdeploy#67] opened 2019-01-23 22:18 UTC
There are commandline arguments to the linuxdeploy executable to explicitly specifc the executable, icon, or desktop file to deploy.

It would be helpful to extend this with another option also for the appdata file, given this is another file often used to enrich appimages (and also recommeded by the appimage spec to be used).

**Comment by goetzc** [comment] 2019-03-10 18:38
This seems to be a duplicate of #31.

**Comment by TheAssassin** [comment] 2019-03-10 18:44
Indeed, it is. Let's close this one as duplicate. Thanks @goetzc.

**Closed by TheAssassin** 2019-03-10 18:44 UTC
