### ISSUE TITLE
Build error: copyright.h: No such file or directory

### ISSUE THREAD

**Issue by devilsclaw** [linuxdeploy/linuxdeploy#212] opened 2022-08-19 18:59 UTC
So I did this:
`git clone --recursive https://github.com/linuxdeploy/linuxdeploy.git`
`cd linuxdeploy`
`mkdir build`
`cd build`
`cmake ..`
`make`

and got this error message

`/home/xxxxx/projects/c_cpp/linuxdeploy/src/core/appdir.cpp:20:10: fatal error: copyright.h: No such file or directory`
`   20 | #include "copyright.h"`

**Comment by TheAssassin** [comment] 2022-08-19 21:07
That same process is working just fine in the CI. So, obviously, you need to provide more information... starting with your distro (and version), a build log etc.

**Comment by devilsclaw** [comment] 2022-08-19 23:38
Recently updated to Ubuntu 22.04 from 21.04

**Comment by lcarlotto** [comment] 2022-10-07 08:27
I have the exact same problem, only the line of code is different.

However, I used the script:
`ci/build.sh`

and the last output rows:
```
Scanning dependencies of target linuxdeploy
Scanning dependencies of target plugin_test
[ 76%] Building CXX object src/CMakeFiles/plugin_test.dir/plugin_test_main.cpp.o
[ 78%] Building CXX object src/CMakeFiles/linuxdeploy.dir/main.cpp.o
[ 80%] Linking CXX executable ../bin/plugin_test
[ 80%] Built target plugin_test
Scanning dependencies of target appdir_test
[ 81%] Building CXX object src/CMakeFiles/appdir_test.dir/appdir_test_main.cpp.o
In file included from ../linuxdeploy/src/appdir_test_main.cpp:10:
../linuxdeploy/src/core/appdir.cpp:21:10: fatal error: copyright.h: File o directory non esistente
   21 | #include "copyright.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/appdir_test.dir/build.make:82: src/CMakeFiles/appdir_test.dir/appdir_test_main.cpp.o] Errore 1
make[1]: *** [CMakeFiles/Makefile2:1532: src/CMakeFiles/appdir_test.dir/all] Errore 2
make[1]: *** Attesa per i processi non terminati....
[ 83%] Building CXX object src/CMakeFiles/linuxdeploy.dir/core.cpp.o
[ 85%] Linking CXX executable ../bin/linuxdeploy
[ 85%] Built target linuxdeploy
make: *** [Makefile:160: all] Errore 2
+ cleanup
+ '[' -d /dev/shm/linuxdeploy-build-gB6ona ']'
+ rm -rf /dev/shm/linuxdeploy-build-gB6ona
```

Run on a virtual machine (VirtualBox) Debian 11.5 x64.

**Comment by lcarlotto** [comment] 2022-10-07 08:57
Even using direct compilation with cmake I have the same problem.

```
mkdir build
cd build
cmake ..
make
```

**Comment by lcarlotto** [comment] 2022-10-07 10:03
By modifying the source code:
`src/core/appdir.cpp`
change:
`#include "copyright.h"`
with:
`#include "linuxdeploy/core/copyright/copyright.h"`
then add subdir:
`mkdir -p include/linuxdeploy/core/copyright`
and copy includes into this new dir:
`cp src/core/copyright/*.h include/linuxdeploy/core/copyright/`

compilation ends successfully.

**Comment by lcarlotto** [comment] 2022-10-10 06:44
attached the build log ...
[linuxdeploy-build.log](https://github.com/linuxdeploy/linuxdeploy/files/9743719/linuxdeploy-build.log)

compilation performed on Debian 11.5 (2 Core, 4Gb RAM), as a guest virtual machine in VirtualBox 6.1.38 environment (latest version):

```
uname -a
Linux debian 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
```

**Comment by iamsergio** [comment] 2024-05-14 11:04
I found that if you run cmake twice, then it builds.
I'm on Ubuntu-22.04 / 3.22.1

**Comment by alexg-k** [comment] 2024-12-13 13:21
I am trying to build on docker and have the same error:

```bash
[...]
58.07 [ 62%] Building CXX object src/CMakeFiles/appdir_test.dir/appdir_test_main.cpp.o
58.32 In file included from /linuxdeploy/src/appdir_test_main.cpp:10:
58.32 /linuxdeploy/src/core/appdir.cpp:20:10: fatal error: copyright.h: No such file or directory
58.32    20 | #include "copyright.h"
58.32       |          ^~~~~~~~~~~~~
58.32 compilation terminated.
58.33 gmake[2]: *** [src/CMakeFiles/appdir_test.dir/build.make:76: src/CMakeFiles/appdir_test.dir/appdir_test_main.cpp.o] Error 1
58.33 gmake[1]: *** [CMakeFiles/Makefile2:1447: src/CMakeFiles/appdir_test.dir/all] Error 2
58.33 gmake: *** [Makefile:146: all] Error 2
```

I am using Debian Bookworm and the current master branch to build.

**Comment by TheAssassin** [comment] 2024-12-13 13:39
The build in Docker still works just fine. This is really odd.

**Comment by alexg-k** [comment] 2024-12-13 13:52
I have an idea on where to look further: 

If packages are not installed by the system package manager, then cmake uses the module `FetchContent`. After the error above I installed `libgtest-dev` and `cimg-dev` via apt and got a different error:
```bash
31.63 [ 96%] Building CXX object tests/core/CMakeFiles/test_elf_file.dir/test_elf_file.cpp.o
31.74 /linuxdeploy/tests/core/test_elf_file.cpp:2:10: fatal error: gmock/gmock.h: No such file or directory
31.74     2 | #include "gmock/gmock.h"
31.74       |          ^~~~~~~~~~~~~~~
31.74 compilation terminated.
31.74 gmake[2]: *** [tests/core/CMakeFiles/test_elf_file.dir/build.make:76: tests/core/CMakeFiles/test_elf_file.dir/test_elf_file.cpp.o] Error 1
31.74 gmake[1]: *** [CMakeFiles/Makefile2:1737: tests/core/CMakeFiles/test_elf_file.dir/all] Error 2
31.74 gmake: *** [Makefile:146: all] Error 2
```
I then installed `libgmock-dev` and build completed sucessfully.

**Comment by TheAssassin** [comment] 2024-12-13 13:54
I just reproduced the bug regarding `copyright.h` _once_. Looks like if the order of operations happens to be right, it works, otherwise it might fail unexpectedly. I'll have a look.

Regarding your last issue, that's entirely expected, dependencies must be installed of course. You can always look into the Dockerfile to see what is being installed in addition to the base system.

**Comment by alexg-k** [comment] 2024-12-13 14:01
It is expected to have the packages installed, but cmake tries to recover using FetchContent and fails to build anyway. Maybe don't try to include FetchContent in this case to get a clearer error message to the problem?

Thank you for your help.

**Comment by TheAssassin** [comment] 2024-12-13 18:46
Should be fixed. If not, please comment.

**Closed** 2024-12-13 18:46 UTC
