### ISSUE TITLE
Qt Plugin Hangs

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [linuxdeploy/linuxdeploy#24] opened 2018-08-26 12:10 UTC
I am trying to use this tool instead of `linuxdeployqt` but it kind of hangs or takes too much time than I could wait for at following step:

**EDIT**: Retried with correct prefix, but same result: hung.

```
-- Running input plugin: qt -- 
Running process: /home/vaibhav/Desktop/build/linuxdeploy-plugin-qt-x86_64.AppImage --appdir AppDir
```

The command I used to package:

```
./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin=qt || return 1
```

`AppDir` structure is as follows:

```
AppDir/
AppDir/usr
AppDir/usr/bin
AppDir/usr/bin/exec_me
AppDir/usr/share
AppDir/usr/share/pixmaps
AppDir/usr/share/pixmaps/exec_me.png
AppDir/usr/share/applications
AppDir/usr/share/applications/exec_me.desktop
```

**Comment by azubieta** [comment] 2018-08-26 12:56
Hi, thanks for reporting. Can you share a link to the code of the app you are trying to pack? For us to reproduce and fix the error?

**Comment by vaibhavpandeyvpz** [comment] 2018-08-26 12:57
@azubieta I wish if I could, but the app is closed source.

**Comment by azubieta** [comment] 2018-08-26 12:59
That's kind of challenging. What about a tarball with the results of "DESTDIR=make install"

**Comment by azubieta** [comment] 2018-08-26 13:00
By the way this is a linuxdeploy-plugin-qt issue so it should be discussed in its own repository.

**Comment by TheAssassin** [comment] 2018-08-26 13:01
@azubieta no more information needed, this is a duplicate of #14.

**Comment by vaibhavpandeyvpz** [comment] 2018-08-26 13:01
@azubieta The `linuxdeploy-plugin-qt` is working for me as standalone. It only hangs when run an input plugin of `linxudeployqt`.

**Closed by TheAssassin** 2018-08-26 13:01 UTC

**Comment by TheAssassin** [comment] 2018-08-26 21:50
@vaibhavpandeyvpz that's the point, the issue is within the subprocess handling of linuxdeploy. See #14 for more information.
