### ISSUE TITLE
Linux Deploy crashing on GitLab CI with "terminate called after throwing an instance of 'std::logic_error'"

### ISSUE THREAD

**Issue by CalcProgrammer1** [linuxdeploy/linuxdeploy#155] opened 2020-11-05 04:46 UTC
```
2020-11-05 04:33:52 (9.79 MB/s) - 'linuxdeploy-plugin-qt-i386.AppImage' saved [6641696/6641696]
+ chmod +x linuxdeploy-i386.AppImage linuxdeploy-plugin-qt-i386.AppImage
+ export QML_SOURCES_PATHS=/builds/CalcProgrammer1/OpenRGB/src
+ QML_SOURCES_PATHS=/builds/CalcProgrammer1/OpenRGB/src
+ ./linuxdeploy-i386.AppImage --appimage-extract-and-run --appdir AppDir -e OpenRGB -i /builds/CalcProgrammer1/OpenRGB/qt/OpenRGB.png -d /builds/CalcProgrammer1/OpenRGB/qt/OpenRGB.desktop
linuxdeploy version 1-alpha (git commit ID b6a1ba2), Travis build 488 built on 2020-10-20 16:04:50 UTC
terminate called after throwing an instance of 'std::logic_error'
  what():  subprocess failed (exit code 1)
+ cleanup
+ '[' -d /tmp/appimage-build-ucyO0s ']'
+ rm -rf /tmp/appimage-build-ucyO0s
```

The full log is here:

https://gitlab.com/CalcProgrammer1/OpenRGB/-/jobs/831292635

I was using this old copy of Linux Deploy for a while now but it's gone offline and all my builds started failing, so I switched back to the main CI build of linuxdeploy.

https://artifacts.assassinate-you.net/artifactory/list/linuxdeploy/travis-456/linuxdeploy-i386.AppImage

Same issue for the 64-bit build.

Build steps:

```
./linuxdeploy-i386.AppImage --appimage-extract-and-run --appdir AppDir -e OpenRGB -i "$REPO_ROOT"/qt/OpenRGB.png -d "$REPO_ROOT"/qt/OpenRGB.desktop 
./linuxdeploy-plugin-qt-i386.AppImage --appimage-extract-and-run --appdir AppDir
./linuxdeploy-i386.AppImage --appimage-extract-and-run --appdir AppDir --output appimage
```

Full script here: https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/scripts/build-appimage-32.sh

**Comment by TheAssassin** [comment] 2020-12-05 02:33
The script does not exist any more...

**Comment by TheAssassin** [comment] 2020-12-09 11:42
Pretty sure this is a duplicate of #154.

**Closed by TheAssassin** 2020-12-09 11:42 UTC
