### ISSUE TITLE
Stuck on "Deploying desktop files"

### ISSUE THREAD

**Issue by jonaski** [linuxdeploy/linuxdeploy#39] opened 2018-10-31 20:53 UTC
I'm having an issue with linuxdeploy.
it gets stuck on "-- Deploying desktop files -- "
I've tried both on opensuse, fedora and ubuntu. All get's stuck at the same place.

Here is the commands I run:

```
set -e
set -x
git clone https://github.com/jonaski/strawberry
pushd strawberry
mkdir build
pushd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make -j$(nproc)
make install DESTDIR=AppDir
wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
wget https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage
wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
chmod +x linuxdeploy*.AppImage
./linuxdeploy-x86_64.AppImage --appdir AppDir -e strawberry -i ../dist/unix/strawberry.png -d ../dist/unix/strawberry.desktop --plugin qt --output appimage
```

If I skip the -d and -i option, It gets stuck on:
"Deploying files into AppDir root directory"

**Comment by azubieta** [comment] 2018-10-31 23:14
An AppImage should include all its dependencies. Not only shared libraries but also other resources such as icons. There is no warranty that the icons that you use will be in every Linux system, therefore, you must also embed them.

Two options came to my mind to achieve it:
 1. Embed the whole icon theme or a portion of it (but it must remain a valid [icon theme](https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html)). Create a script to properly export the XDG_DATA_DIR environment variable and execute your binary.
 2. Just copy the icons and modify your application to properly load them as a fallback.

Still, we must find out why icons from theme are not being loaded properly.

**Comment by TheAssassin** [comment] 2018-11-03 00:36
The issue is in our desktop file parser. The library we use tries to read the desktop file forever, somehow it doesn't manage to read it properly. I will try to work around that.

**Comment by TheAssassin** [comment] 2018-11-03 00:42
The issue is actually that the INI parser library doesn't like lines > 256 bytes, its reading logic is apparently flawed. See https://github.com/Turbine1991/cpp-feather-ini-parser/blob/4659a6b9088bfdf04ea69e63a18cc6d2f14f3f7b/INI.h#L30. By increasing that value to a very high value, the issue can be resolved easily.

Will open an issue there, and insert the link here.

**Comment by TheAssassin** [comment] 2018-11-07 19:10
Pushed a temporary workaround that will patch the INI parser on Travis in 6112a63. It's not very elegant and definitely not for long-term, but it'll do until I can provide a better solution.

**Closed** 2018-11-09 22:07 UTC
Labels: blocked by upstream, bug, confirmed

**Comment by TheAssassin** [comment] 2018-11-10 00:57
Should work now. I put in quite some effort to write a proper desktop file parser in C++. It provides the minimum set of functionality required for linuxdeploy right now, and it's unit tested nearly completely.

We will probably make it a separate project, as there's really a lack for a feature complete, reliable and modern desktop file parser.

We intend to use the parser in other projects as well, and will add new features there then.
